//
//  Unit tests for sdr_pvt.c.
//
#include "test_sdr.h"

#define NAVDATA_FILE ".pocket_navdata.csv"

extern double sdr_epoch;

// remove files generated by these tests ---------------------------------------
static void cleanup_files(void)
{
    remove(NAVDATA_FILE);
}

// create initialized PVT test object ------------------------------------------
static sdr_pvt_t *new_test_pvt(sdr_rcv_t *rcv)
{
    sdr_pvt_t *pvt;
    
    cleanup_files();
    memset(rcv, 0, sizeof(*rcv));
    pvt = sdr_pvt_new(rcv);
    TEST_ASSERT_TRUE(pvt != NULL);
    
    memset(pvt->obs->data, 0, sizeof(obsd_t) * pvt->obs->nmax);
    pvt->obs->n = 0;
    memset(pvt->nav->eph, 0, sizeof(eph_t) * pvt->nav->nmax);
    memset(pvt->nav->geph, 0, sizeof(geph_t) * pvt->nav->ngmax);
    memset(pvt->nav->seph, 0, sizeof(seph_t) * pvt->nav->nsmax);
    memset(pvt->nav->alm, 0, sizeof(alm_t) * pvt->nav->namax);
    memset(pvt->sol, 0, sizeof(sol_t));
    memset(pvt->ssat, 0, sizeof(ssat_t) * MAXSAT);
    pvt->time = gpst2time(2200, 1000.0);
    pvt->ix = 0;
    pvt->nsat = pvt->nch = 0;
    pvt->latency = 0.0;
    pvt->count[0] = pvt->count[1] = pvt->count[2] = 0;
    pvt->last_valid = 0;
    
    return pvt;
}

// setup locked channel for PVT tests ------------------------------------------
static void setup_channel(sdr_ch_t *ch, sdr_trk_t *trk, sdr_nav_t *nav)
{
    memset(ch, 0, sizeof(*ch));
    memset(trk, 0, sizeof(*trk));
    memset(nav, 0, sizeof(*nav));
    ch->state = SDR_STATE_LOCK;
    ch->no = 2;
    ch->rf_ch = 0;
    strcpy(ch->sat, "G01");
    strcpy(ch->sig, "L1CA");
    ch->prn = 1;
    ch->fc = 1575.42e6;
    ch->T = 1e-3;
    ch->lock = 3000;
    ch->cn0 = 45.0;
    ch->tow = 999000;
    ch->tow_v = 1;
    ch->week = 2200;
    ch->coff = 1e-4;
    ch->fd = -12.5;
    ch->adr = -1234.5;
    ch->obs_idx = 0;
    ch->trk = trk;
    ch->nav = nav;
    ch->nav->fsync = 2000;
}

// test sdr_pvt_new() and sdr_pvt_free() ---------------------------------------
static void test_sdr_pvt_new_free_api(void)
{
    sdr_rcv_t rcv;
    sdr_pvt_t *pvt = new_test_pvt(&rcv);
    
    TEST_ASSERT_TRUE(pvt->obs != NULL);
    TEST_ASSERT_TRUE(pvt->obs->data != NULL);
    TEST_ASSERT_TRUE(pvt->obs->nmax >= 256);
    TEST_ASSERT_TRUE(pvt->nav != NULL);
    TEST_ASSERT_TRUE(pvt->nav->eph != NULL);
    TEST_ASSERT_TRUE(pvt->nav->geph != NULL);
    TEST_ASSERT_TRUE(pvt->nav->seph != NULL);
    TEST_ASSERT_TRUE(pvt->nav->alm != NULL);
    TEST_ASSERT_TRUE(pvt->sol != NULL);
    TEST_ASSERT_TRUE(pvt->ssat != NULL);
    TEST_ASSERT_TRUE(pvt->rtcm != NULL);
    TEST_ASSERT_TRUE(pvt->rcv == &rcv);
    
    sdr_pvt_free(pvt);
    sdr_pvt_free(NULL);
    cleanup_files();
}

// test sdr_pvt_solstr() -------------------------------------------------------
static void test_sdr_pvt_solstr_api(void)
{
    sdr_rcv_t rcv;
    sdr_pvt_t *pvt = new_test_pvt(&rcv);
    char buff[128];
    double ep[6] = {2026, 6, 4, 1, 2, 3.0};
    double pos[3] = {35.0 * D2R, 139.0 * D2R, 123.4};
    
    pvt->time = epoch2time(ep);
    pvt->sol->ns = 0;
    pvt->nsat = 0;
    sdr_pvt_solstr(pvt, buff, sizeof(buff));
    TEST_ASSERT_TRUE(strstr(buff, "2026-06-04 01:02:03.0") != NULL);
    TEST_ASSERT_TRUE(strstr(buff, "0/0") != NULL);
    TEST_ASSERT_TRUE(strstr(buff, "---") != NULL);
    
    pos2ecef(pos, pvt->sol->rr);
    pvt->sol->time = epoch2time(ep);
    pvt->sol->stat = SOLQ_SINGLE;
    pvt->sol->ns = 7;
    pvt->nsat = 9;
    sdr_pvt_solstr(pvt, buff, sizeof(buff));
    TEST_ASSERT_TRUE(strstr(buff, "35.00000000") != NULL);
    TEST_ASSERT_TRUE(strstr(buff, "139.00000000") != NULL);
    TEST_ASSERT_TRUE(strstr(buff, "7/9") != NULL);
    TEST_ASSERT_TRUE(strstr(buff, "FIX") != NULL);
    
    sdr_pvt_free(pvt);
    cleanup_files();
}

// test sdr_pvt_udobs() epoch initialization -----------------------------------
static void test_sdr_pvt_udobs_init_epoch_api(void)
{
    sdr_rcv_t rcv;
    sdr_pvt_t *pvt = new_test_pvt(&rcv);
    sdr_ch_t ch;
    sdr_trk_t trk;
    sdr_nav_t nav;
    int64_t ix = 100000;
    
    setup_channel(&ch, &trk, &nav);
    pvt->ix = 0;
    
    sdr_pvt_udobs(pvt, ix, &ch);
    
    TEST_ASSERT_TRUE(pvt->ix > 0);
    TEST_ASSERT_EQ_INT(0, pvt->obs->n);
    TEST_ASSERT_EQ_INT(0, pvt->nch);
    
    sdr_pvt_free(pvt);
    cleanup_files();
}

// test sdr_pvt_udobs() observation update -------------------------------------
static void test_sdr_pvt_udobs_update_api(void)
{
    sdr_rcv_t rcv;
    sdr_pvt_t *pvt = new_test_pvt(&rcv);
    sdr_ch_t ch;
    sdr_trk_t trk;
    sdr_nav_t nav;
    int64_t ix = 123456;
    
    setup_channel(&ch, &trk, &nav);
    pvt->time = gpst2time(ch.week, ch.tow * 1e-3 + 0.075);
    pvt->ix = ix;
    
    sdr_pvt_udobs(pvt, ix, &ch);
    
    TEST_ASSERT_EQ_INT(1, pvt->nch);
    TEST_ASSERT_EQ_INT(1, pvt->obs->n);
    TEST_ASSERT_EQ_INT(satid2no("G01"), pvt->obs->data[0].sat);
    TEST_ASSERT_EQ_INT(CODE_L1C, pvt->obs->data[0].code[0]);
    TEST_ASSERT_TRUE(pvt->obs->data[0].P[0] > 0.0);
    TEST_ASSERT_NEAR(ch.fd, pvt->obs->data[0].D[0], 1e-6);
    TEST_ASSERT_TRUE(pvt->obs->data[0].SNR[0] > 0);
    TEST_ASSERT_TRUE((pvt->obs->data[0].LLI[0] & 1) == 0);
    TEST_ASSERT_TRUE((pvt->obs->data[0].LLI[0] & 2) == 0);
    
    sdr_pvt_free(pvt);
    cleanup_files();
}

// test sdr_pvt_udobs() invalid observations -----------------------------------
static void test_sdr_pvt_udobs_invalid_api(void)
{
    sdr_rcv_t rcv;
    sdr_pvt_t *pvt = new_test_pvt(&rcv);
    sdr_ch_t ch;
    sdr_trk_t trk;
    sdr_nav_t nav;
    int64_t ix = 123456;
    
    setup_channel(&ch, &trk, &nav);
    pvt->ix = ix;
    ch.tow_v = 0;
    sdr_pvt_udobs(pvt, ix, &ch);
    
    TEST_ASSERT_EQ_INT(1, pvt->nch);
    TEST_ASSERT_EQ_INT(0, pvt->obs->n);
    
    ch.tow_v = 1;
    strcpy(ch.sat, "R-7");
    sdr_pvt_udobs(pvt, ix, &ch);
    TEST_ASSERT_EQ_INT(2, pvt->nch);
    TEST_ASSERT_EQ_INT(0, pvt->obs->n);
    
    sdr_pvt_free(pvt);
    cleanup_files();
}

// test sdr_pvt_udnav() --------------------------------------------------------
static void test_sdr_pvt_udnav_api(void)
{
    sdr_rcv_t rcv;
    sdr_pvt_t *pvt = new_test_pvt(&rcv);
    sdr_ch_t ch;
    sdr_trk_t trk;
    sdr_nav_t nav;
    
    setup_channel(&ch, &trk, &nav);
    strcpy(ch.sat, "???");
    ch.nav->type = 3;
    sdr_pvt_udnav(pvt, &ch);
    TEST_ASSERT_EQ_INT(0, pvt->count[2]);
    
    strcpy(ch.sat, "G01");
    strcpy(ch.sig, "L1CA");
    ch.nav->type = 0;
    sdr_pvt_udnav(pvt, &ch);
    TEST_ASSERT_EQ_INT(0, pvt->count[2]);
    
    sdr_pvt_free(pvt);
    cleanup_files();
}

// test sdr_pvt_udsol() --------------------------------------------------------
static void test_sdr_pvt_udsol_api(void)
{
    sdr_rcv_t rcv;
    sdr_pvt_t *pvt = new_test_pvt(&rcv);
    int64_t ix0 = 200000;
    
    rcv.nch = 1;
    pvt->ix = ix0;
    pvt->nch = 0;
    pvt->obs->n = 0;
    
    sdr_pvt_udsol(pvt, ix0);
    TEST_ASSERT_EQ_INT(ix0, pvt->ix);
    
    pvt->nch = 1;
    sdr_pvt_udsol(pvt, ix0);
    TEST_ASSERT_EQ_INT(ix0 + (int64_t)(sdr_epoch / SDR_CYC), pvt->ix);
    TEST_ASSERT_EQ_INT(0, pvt->nch);
    TEST_ASSERT_EQ_INT(0, pvt->obs->n);
    TEST_ASSERT_NEAR(0.0, pvt->latency, 1e-12);
    
    sdr_pvt_free(pvt);
    cleanup_files();
}

// main ------------------------------------------------------------------------
int main(void)
{
    cleanup_files();
    TEST_RUN(test_sdr_pvt_new_free_api);
    TEST_RUN(test_sdr_pvt_solstr_api);
    TEST_RUN(test_sdr_pvt_udobs_init_epoch_api);
    TEST_RUN(test_sdr_pvt_udobs_update_api);
    TEST_RUN(test_sdr_pvt_udobs_invalid_api);
    TEST_RUN(test_sdr_pvt_udnav_api);
    TEST_RUN(test_sdr_pvt_udsol_api);
    cleanup_files();
    return 0;
}
