//
//  Unit tests for sdr_array.c.
//
#include "test_sdr.h"

#define ARRAY_STATE_FILE "test_sdr_array_state.tmp"
#define ARRAY_GEOM_FILE  "test_sdr_array_geom.tmp"

// remove files generated by these tests ---------------------------------------
static void cleanup_files(void)
{
    remove(ARRAY_STATE_FILE);
    remove(ARRAY_GEOM_FILE);
}

// allocate IF data buffer for array tests -------------------------------------
static sdr_buff_t *test_buff_new(int N)
{
    sdr_buff_t *buff = (sdr_buff_t *)sdr_malloc(sizeof(sdr_buff_t));
    
    buff->data = (sdr_cpx8_t *)sdr_malloc(sizeof(sdr_cpx8_t) * N);
    buff->IQ = 2;
    buff->N = N;
    return buff;
}

// free IF data buffer for array tests -----------------------------------------
static void test_buff_free(sdr_buff_t *buff)
{
    if (!buff) return;
    sdr_free(buff->data);
    sdr_free(buff);
}

// setup minimal receiver for sdr_arch tests -----------------------------------
static void setup_arch_rcv(sdr_rcv_t *rcv, sdr_array_t *array, int N)
{
    memset(rcv, 0, sizeof(*rcv));
    rcv->fs = 4e6;
    rcv->N = N;
    rcv->nrfch = 2;
    rcv->narch = 1;
    rcv->array = array;
    rcv->rfch[0].fo = 1575.42e6;
    rcv->rfch[1].fo = 1575.42e6;
    rcv->rfch[0].IQ = rcv->rfch[1].IQ = 2;
    rcv->rfch[0].bits = rcv->rfch[1].bits = 4;
    rcv->buff[0] = test_buff_new(N);
    rcv->buff[1] = test_buff_new(N);
    rcv->buff[2] = test_buff_new(N);
}

// free minimal receiver for sdr_arch tests ------------------------------------
static void free_arch_rcv(sdr_rcv_t *rcv)
{
    for (int i = 0; i < 3; i++) {
        test_buff_free(rcv->buff[i]);
        rcv->buff[i] = NULL;
    }
}

// test sdr_array_new() and sdr_array_free() -----------------------------------
static void test_sdr_array_new_free_api(void)
{
    sdr_array_t *array = sdr_array_new(3, 1);
    
    TEST_ASSERT_TRUE(array != NULL);
    TEST_ASSERT_EQ_INT(3, array->nrfch);
    TEST_ASSERT_EQ_INT(1, array->freq);
    TEST_ASSERT_EQ_INT(SDR_CALIB_BOTH, array->calib_mode);
    TEST_ASSERT_EQ_INT(1, array->ant_ena[0]);
    TEST_ASSERT_EQ_INT(1, array->ant_ena[1]);
    TEST_ASSERT_EQ_INT(1, array->ant_ena[2]);
    TEST_ASSERT_EQ_INT(0, array->ant_ena[3]);
    
    sdr_array_free(array);
    sdr_array_free(NULL);
}

// test sdr_array_ant_pos() ----------------------------------------------------
static void test_sdr_array_ant_pos_api(void)
{
    sdr_array_t *array = sdr_array_new(3, 0);
    double ant_pos[SDR_MAX_RFCH * 3] = {
        0.0, 0.0, 0.0,
        0.1, 0.0, 0.0,
        0.0, 0.2, 0.0
    };
    int ant_ena[SDR_MAX_RFCH] = {1, 0, 2};
    
    TEST_ASSERT_EQ_INT(1, sdr_array_ant_pos(array, ant_pos, ant_ena));
    TEST_ASSERT_NEAR(0.1, array->ant_pos[1][0], 1e-12);
    TEST_ASSERT_NEAR(0.2, array->ant_pos[2][1], 1e-12);
    TEST_ASSERT_EQ_INT(1, array->ant_ena[0]);
    TEST_ASSERT_EQ_INT(0, array->ant_ena[1]);
    TEST_ASSERT_EQ_INT(1, array->ant_ena[2]);
    
    ant_ena[0] = 0;
    TEST_ASSERT_EQ_INT(0, sdr_array_ant_pos(array, ant_pos, ant_ena));
    
    sdr_array_free(array);
}

// test sdr_array_run(), set_mode(), set() and stat() --------------------------
static void test_sdr_array_run_mode_set_stat_api(void)
{
    sdr_array_t *array = sdr_array_new(2, 0);
    sdr_array_t *array_1ch = sdr_array_new(1, 0);
    double rpy_in[3] = {0.01, -0.02, 0.03};
    double bias_in[SDR_MAX_RFCH] = {0.0, 0.12};
    double rpy[3], bias[SDR_MAX_RFCH], rms = -1.0;
    int nep = -1;
    
    TEST_ASSERT_EQ_INT(0, sdr_array_run(array_1ch, 1));
    TEST_ASSERT_EQ_INT(0, sdr_array_set(array_1ch, rpy_in, bias_in));
    
    TEST_ASSERT_EQ_INT(1, sdr_array_set(array, rpy_in, bias_in));
    TEST_ASSERT_EQ_INT(0, sdr_array_stat(array, rpy, bias, &rms, &nep));
    TEST_ASSERT_NEAR(rpy_in[0], rpy[0], 1e-12);
    TEST_ASSERT_NEAR(rpy_in[1], rpy[1], 1e-12);
    TEST_ASSERT_NEAR(rpy_in[2], rpy[2], 1e-12);
    TEST_ASSERT_NEAR(0.0, bias[0], 1e-12);
    TEST_ASSERT_NEAR(bias_in[1], bias[1], 1e-12);
    
    TEST_ASSERT_EQ_INT(1, sdr_array_set_mode(array, SDR_CALIB_BIAS));
    TEST_ASSERT_EQ_INT(SDR_CALIB_BIAS, array->calib_mode);
    TEST_ASSERT_EQ_INT(1, sdr_array_set_mode(array, SDR_CALIB_RPY));
    TEST_ASSERT_EQ_INT(SDR_CALIB_RPY, array->calib_mode);
    TEST_ASSERT_EQ_INT(0, sdr_array_set_mode(array, -1));
    
    TEST_ASSERT_EQ_INT(1, sdr_array_run(array, 1));
    TEST_ASSERT_EQ_INT(1, array->calib_run);
    TEST_ASSERT_EQ_INT(1, sdr_array_stat(array, rpy, bias, &rms, &nep));
    TEST_ASSERT_NEAR(0.0, rpy[0], 1e-12);
    TEST_ASSERT_EQ_INT(0, nep);
    TEST_ASSERT_NEAR(0.0, rms, 1e-12);
    TEST_ASSERT_EQ_INT(1, sdr_array_run(array, 2));
    TEST_ASSERT_EQ_INT(0, array->calib_run);
    
    sdr_array_free(array_1ch);
    sdr_array_free(array);
}

// test sdr_array_calib() edge cases -------------------------------------------
static void test_sdr_array_calib_edge_api(void)
{
    sdr_array_t *array = sdr_array_new(2, 0);
    double rr[3] = {0.0, 0.0, 0.0};
    
    TEST_ASSERT_EQ_INT(1, sdr_array_run(array, 1));
    sdr_array_calib(array, NULL, 0, NULL, rr);
    TEST_ASSERT_EQ_INT(0, array->nep);
    TEST_ASSERT_NEAR(0.0, array->rms, 1e-12);
    
    sdr_array_free(array);
}

// test sdr_array_save() and sdr_array_load() ----------------------------------
static void test_sdr_array_save_load_api(void)
{
    sdr_array_t *array = sdr_array_new(3, 0);
    sdr_array_t *loaded = sdr_array_new(3, 0);
    double rpy_in[3] = {1.0 * D2R, -2.0 * D2R, 3.0 * D2R};
    double bias_in[SDR_MAX_RFCH] = {0.0, 0.1234, -0.5678};
    double rpy[3], bias[SDR_MAX_RFCH], rms;
    int nep;
    
    cleanup_files();
    TEST_ASSERT_EQ_INT(0, sdr_array_save(array, ARRAY_STATE_FILE));
    
    TEST_ASSERT_EQ_INT(1, sdr_array_set(array, rpy_in, bias_in));
    TEST_ASSERT_EQ_INT(1, sdr_array_save(array, ARRAY_STATE_FILE));
    TEST_ASSERT_EQ_INT(1, sdr_array_load(loaded, ARRAY_STATE_FILE));
    TEST_ASSERT_EQ_INT(0, sdr_array_load(loaded, "no_such_array_state.tmp"));
    
    TEST_ASSERT_EQ_INT(0, sdr_array_stat(loaded, rpy, bias, &rms, &nep));
    TEST_ASSERT_NEAR(rpy_in[0], rpy[0], 1e-5);
    TEST_ASSERT_NEAR(rpy_in[1], rpy[1], 1e-5);
    TEST_ASSERT_NEAR(rpy_in[2], rpy[2], 1e-5);
    TEST_ASSERT_NEAR(bias_in[1], bias[1], 1e-4);
    TEST_ASSERT_NEAR(bias_in[2], bias[2], 1e-4);
    
    sdr_array_free(loaded);
    sdr_array_free(array);
    cleanup_files();
}

// test sdr_array_geom_save() and sdr_array_geom_load() ------------------------
static void test_sdr_array_geom_api(void)
{
    double ant_pos[9] = {
        0.0, 0.0, 0.0,
        0.1, 0.2, 0.3,
       -0.1, 0.4, 0.5
    };
    double loaded[9] = {0};
    
    cleanup_files();
    TEST_ASSERT_EQ_INT(3, sdr_array_geom_save(ARRAY_GEOM_FILE, ant_pos, 3));
    TEST_ASSERT_EQ_INT(2, sdr_array_geom_load(ARRAY_GEOM_FILE, loaded, 2));
    TEST_ASSERT_NEAR(0.1, loaded[3], 1e-12);
    TEST_ASSERT_NEAR(0.2, loaded[4], 1e-12);
    TEST_ASSERT_NEAR(0.3, loaded[5], 1e-12);
    TEST_ASSERT_EQ_INT(0, sdr_array_geom_load("no_such_array_geom.tmp",
        loaded, 2));
    cleanup_files();
}

// test sdr_arch_set_beam(), get_beam() and free() -----------------------------
static void test_sdr_arch_beam_api(void)
{
    sdr_array_t *array = sdr_array_new(2, 0);
    sdr_rcv_t rcv;
    double az = 0.0, el = 0.0;
    
    setup_arch_rcv(&rcv, array, 4);
    sdr_arch_set_beam(rcv.arch, &rcv, 0.25, 0.75, 1.0);
    TEST_ASSERT_NEAR(0.5, rcv.arch[0].scale, 1e-12);
    TEST_ASSERT_TRUE(rcv.arch[0].w[0] != 0);
    TEST_ASSERT_TRUE(rcv.arch[0].w[2] != 0);
    
    sdr_arch_get_beam(rcv.arch, &az, &el);
    TEST_ASSERT_NEAR(0.25, az, 1e-12);
    TEST_ASSERT_NEAR(0.75, el, 1e-12);
    
    sdr_arch_free(rcv.arch);
    TEST_ASSERT_NEAR(0.0, rcv.arch[0].scale, 1e-12);
    TEST_ASSERT_EQ_INT(0, rcv.arch[0].w[0]);
    
    free_arch_rcv(&rcv);
    sdr_array_free(array);
}

// test sdr_arch_combine() -----------------------------------------------------
static void test_sdr_arch_combine_api(void)
{
    sdr_array_t *array = sdr_array_new(2, 0);
    sdr_rcv_t rcv;
    
    setup_arch_rcv(&rcv, array, 4);
    sdr_arch_set_beam(rcv.arch, &rcv, 0.0, PI / 2, 1.0);
    for (int i = 0; i < rcv.N; i++) {
        rcv.buff[0]->data[i] = SDR_CPX8(2, 0);
        rcv.buff[1]->data[i] = SDR_CPX8(2, 0);
        rcv.buff[2]->data[i] = SDR_CPX8(0, 0);
    }
    
    sdr_arch_combine(rcv.arch, &rcv, 0);
    for (int i = 0; i < rcv.N; i++) {
        TEST_ASSERT_EQ_INT(2, SDR_CPX8_I(rcv.buff[2]->data[i]));
        TEST_ASSERT_EQ_INT(0, SDR_CPX8_Q(rcv.buff[2]->data[i]));
    }
    
    sdr_arch_free(rcv.arch);
    rcv.buff[2]->data[0] = SDR_CPX8(3, 1);
    sdr_arch_combine(rcv.arch, &rcv, 0);
    TEST_ASSERT_EQ_INT(3, SDR_CPX8_I(rcv.buff[2]->data[0]));
    TEST_ASSERT_EQ_INT(1, SDR_CPX8_Q(rcv.buff[2]->data[0]));
    
    free_arch_rcv(&rcv);
    sdr_array_free(array);
}

// main ------------------------------------------------------------------------
int main(void)
{
    cleanup_files();
    TEST_RUN(test_sdr_array_new_free_api);
    TEST_RUN(test_sdr_array_ant_pos_api);
    TEST_RUN(test_sdr_array_run_mode_set_stat_api);
    TEST_RUN(test_sdr_array_calib_edge_api);
    TEST_RUN(test_sdr_array_save_load_api);
    TEST_RUN(test_sdr_array_geom_api);
    TEST_RUN(test_sdr_arch_beam_api);
    TEST_RUN(test_sdr_arch_combine_api);
    cleanup_files();
    
    return 0;
}
