all:
	make -C pocket_scan
	make -C pocket_conf
	make -C pocket_dump
	make -C pocket_acq
	make -C pocket_trk
	make -C pocket_snap
clean:
	make -C pocket_scan clean
	make -C pocket_conf clean
	make -C pocket_dump clean
	make -C pocket_acq clean
	make -C pocket_trk clean
	make -C pocket_snap clean
install:
	make -C pocket_scan install
	make -C pocket_conf install
	make -C pocket_dump install
	make -C pocket_acq install
	make -C pocket_trk install
	make -C pocket_snap install

