#
# pocket_trk system options
#
epoch       = 1.0      # epoch interval for PVT (s)
lag_epoch   = 0.5      # max epoch lag for PVT (s)
el_mask     = 15       # elevation mask for PVT (deg)
sp_corr     = 0.2      # correlator spacing (chip)
t_acq       = 0.02     # integration time for acquisition (s)
t_dll       = 0.02     # integration time for DLL (s)
b_dll       = 0.5      # DLL loop filter bandwidth (Hz)
b_pll       = 10.0     # PLL loop filter bandwidth (Hz)
b_fll_w     = 10.0     # FLL loop filter bandwidth wide (Hz)
b_fll_n     = 5.0      # FLL loop filter bandwidth narrow (Hz)
max_dop     = 10000.0  # max Doppler frequency to seach signal (Hz)
thres_cn0_l = 35.0     # C/N0 threshold for signal locked (dB-Hz)
thres_cn0_u = 30.5     # C/N0 threshold for signal lost (dB-Hz)
thres_pli   = 0.25     # carrier lock detector threshold (cos 2*phi)
lost_th     = 4        # lost decision count (C/N0/PLI windows of T_CN0)
bump_jump   = 1        # Bump jump for BOC modulation
max_acq     = 4.0      # max code cycle for all-channel acquisition (ms)
