//
//  Pocket SDR C AP - GNSS Signal Tracking and NAV data decoding
//
//  Author:
//  T.TAKASU
//
//  History:
//  2022-07-05  1.0  port pocket_trk.py to C.
//  2022-08-08  1.1  add option -w, -d
//  2023-12-15  1.2  support multi-threading
//  2023-12-25  1.3  add -r option for raw SDR device data
//  2023-12-28  1.4  set binary mode to stdin for Windows
//  2024-01-12  1.5  update receiver status style
//  2024-01-16  1.6  add -l option, delete -q option
//  2024-01-25  1.7  add acquisition assist
//  2024-02-08  1.8  separate SDR receiver functions to sdr_rcv.c
//  2024-02-20  1.9  modify -fi option, add -I option
//  2024-04-04  1.10 add -u, -p and -c options
//
#include <signal.h>
#ifdef WIN32
#include <fcntl.h>
#endif
#include "pocket_dev.h"
#include "pocket_sdr.h"

// constants and macros ---------------------------------------------------------
#define MAX_DOP    5000.0       // default max Doppler for acquisition (Hz) 
#define FFTW_WISDOM "../python/fftw_wisdom.txt"

// usage text ------------------------------------------------------------------
static const char *usage_text[] = {
    "Usage: pocket_trk [-sig sig [-fi freq] -prn prn[,...] ...] [-r] [-toff toff]",
    "       [-f freq] [-d freq[,freq]] [-IQ|-I|-IQI|-IIQ] [-ti tint]",
    "       [-u] [-p bus,[,port] [-c conf_file]",
    "       [-log path[,level]] [-nmea path[,tint]] [-rtcm path[,tint]] [-w file]",
    "       [file]", NULL
};

// interrupt flag --------------------------------------------------------------
static volatile uint8_t intr = 0;

// signal handler --------------------------------------------------------------
static void sig_func(int sig)
{
    intr = 1;
    signal(sig, sig_func);
}

// show usage ------------------------------------------------------------------
static void show_usage(void)
{
    for (int i = 0; usage_text[i]; i++) {
        printf("%s\n", usage_text[i]);
    }
    exit(0);
}

// separate path and interval --------------------------------------------------
static void sep_path(const char *arg, char *path, double *tint)
{
    char buff[1024], *p;
    sprintf(buff, "%.1023s", arg);
    if ((p = strchr(buff, ','))) {
        sscanf(p, ",%lf", tint);
        *p = '\0';
    }
    strcpy(path, buff);
}

//------------------------------------------------------------------------------
//
//   Synopsis
//
//     pocket_trk [-sig sig [-fi freq] -prn prn[,...] ...] [-r] [-toff toff]
//         [-f freq] [-d freq[,freq]] [-IQ|-I|-IQI|-IIQ] [-ti tint]
//         [-u] [-p bus,[,port] [-c conf_file]
//         [-log path[,level]] [-nmea path[,tint]] [-rtcm path[,tint]] [-w file]
//         [file]
//
//   Description
//
//     It searchs and tracks GNSS signals in digital IF data and decode
//     navigation data in the signals.
//
//   Options ([]: default)
//
//     -sig sig [-fi freq] -prn prn[,...] ...
//         A GNSS signal type ID (L1CA, L2CM, ...) and a PRN number list of the
//         signal. For signal type IDs, refer pocket_acq.py manual. The PRN
//         number list shall be PRN numbers or PRN number ranges like 1-32 with
//         the start and the end numbers. They are separated by ",". For
//         GLONASS FDMA signals (G1CA, G2CA), the PRN number is treated as the
//         FCN (frequency channel number). The pair of a signal type ID and a PRN
//         number list can be repeated for multiple GNSS signals to be tracked.
//
//     -u
//
//     -r
//         Input raw SDR device data format generated by Pocket SDR RF-frontend.
//         The data can be captured by pocket_dump with the -r option.
//         Without the option, input data are handled as a series of int8_t
//         (I-sampling) or interleaved int8_t (IQ-sampling) as the format.
//
//     -toff toff
//         Time offset from the start of the digital IF data in s. [0.0]
//
//     -f freq
//         Sampling frequency of the digital IF data in MHz. [12.0]
//
//     -d freq[,freq]
//         Reference and max Doppler frequencies to search the signal in Hz.
//         As default, the range of the Doppler frequencies is -5 kHz to +5 kHz.
//         [0.0, 5000.0]
//
//     -IQ|-I|-IQI|-IIQ
//         Specify sampling types. (-IQ: IQ-samping for both CH1 and CH2,
//         -I: I-sampling for both CH1 and CH2, -IQI: IQ-sampline for CH1 and
//         I-sampling for CH2, -IIQ: I-sampling for CH1 and IQ-sampling for
//         CH2) The sampling type for CH2 is ignored without -r option.
//         [IQ-sampling for both CH1 and CH2]
//
//     -ti tint
//         Specify update interval of the signal tracking status in seconds.
//         If 0 specified, the signal tracking status is suppressed. [0.1]
//
//     -u
//         Directly read IF data from a USB SDR device.
//
//     -p bus[,port]
//         USB bus and port number of the USB SDR device. Ignored without -u
//         option.
//
//     -c conf_file
//         Configure the USB SDR device with a device configuration file before 
//         capturing. Ignored without -u option.
//
//     -log path[,level]
//         A stream path to write the signal tracking log. The log includes
//         decoded navigation data and code offset, including navigation data
//         decoded. To specify the log level, add ",<level>" after the path.
//         The default log level is 3.
//         The stream path should be one of the followings.
//
//         (1) local file  file path without ':'. The file path can be contain
//             time keywords (%Y, %m, %d, %h, %M) as same as the RTKLIB stream.
//         (2) TCP server  :port
//         (3) TCP client  address:port
//
//     -nmea path[,tint]
//         A stream path to write PVT solutions as NMEA GNRMC, GNGGA and GNGSV
//         sentences. To specify the interval of the PVT solutions in seconds,
//         add ",<tint>" after the path. The default interval is 1 sec. The
//         stream path is as same as the -log option.
//         
//         To be implemented.
//
//     -rtcm path[,tint]
//         A stream path to write raw observation and navigation data as RTCM3.3
//         messages. To specify the interval of the raw observation data in
//         seconds, add ",<tint>" after the path. The stream path is as same
//         as the -log option.
//
//         To be implemented.
//
//     -w file
//         Specify the FFTW wisdowm file. [../python/fftw_wisdom.txt]
//
//     [file]
//         A file path of the input digital IF data. The format should be a
//         series of int8_t (signed byte) for real-sampling (I-sampling),
//         interleaved int8_t for complex-sampling (IQ-sampling) or raw SDR
//         device data. The Pocket SDR RF-frontend and pocket_dump can be used
//         to capture such digital IF data. If the option omitted, the input
//         is taken from stdin.
//
int main(int argc, char **argv)
{
    void *dp = NULL;
    int prns[SDR_MAX_NCH], nch = 0, fmt = SDR_FMT_INT8, IQ[2] = {2, 2};
    int dev_type = SDR_DEV_FILE, bus = -1, port = -1;
    double fif = 0.0, fi[SDR_MAX_NCH] = {0}, fs = 12e6, toff = 0.0;
    double tint[3] = {0.1, 1.0, 1.0}, dop[2] = {0.0, MAX_DOP}, log_lvl = 3.0;
    const char *sig = "L1CA", *sigs[SDR_MAX_NCH];
    const char *file = "", *fftw_wisdom = FFTW_WISDOM, *conf_file = "";
    char paths[3][1024] = {{0}};
    
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "-sig") && i + 1 < argc) {
            sig = argv[++i];
        }
        else if (!strcmp(argv[i], "-fi") && i + 1 < argc) {
            fif = atof(argv[++i]) * 1e6;
        }
        else if (!strcmp(argv[i], "-prn") && i + 1 < argc) {
            int nums[SDR_MAX_NCH];
            int n = sdr_parse_nums(argv[++i], nums);
            for (int j = 0; j < n && nch < SDR_MAX_NCH; j++) {
                sigs[nch] = sig;
                fi[nch] = fif;
                prns[nch++] = nums[j];
            }
        }
        else if (!strcmp(argv[i], "-toff") && i + 1 < argc) {
            toff = atof(argv[++i]);
        }
        else if (!strcmp(argv[i], "-f") && i + 1 < argc) {
            fs = atof(argv[++i]) * 1e6;
        }
        else if (!strcmp(argv[i], "-d") && i + 1 < argc) {
            sscanf(argv[++i], "%lf,%lf", dop, dop + 1);
        }
        else if (!strcmp(argv[i], "-r")) {
            fmt = SDR_FMT_RAW8;
        }
        else if (!strcmp(argv[i], "-IQ")) {
            IQ[0] = IQ[1] = 2;
        }
        else if (!strcmp(argv[i], "-I")) {
            IQ[0] = IQ[1] = 1;
        }
        else if (!strcmp(argv[i], "-IIQ")) {
            IQ[0] = 1;
            IQ[1] = 2;
        }
        else if (!strcmp(argv[i], "-IQI")) {
            IQ[0] = 2;
            IQ[1] = 1;
        }
        else if (!strcmp(argv[i], "-ti") && i + 1 < argc) {
            tint[0] = atof(argv[++i]);
        }
        else if (!strcmp(argv[i], "-u")) {
            dev_type = SDR_DEV_USB;
        }
        else if (!strcmp(argv[i], "-p") && i + 1 < argc) {
            sscanf(argv[++i], "%d,%d", &bus, &port);
        }
        else if (!strcmp(argv[i], "-c") && i + 1 < argc) {
            conf_file = argv[++i];
        }
        else if (!strcmp(argv[i], "-w") && i + 1 < argc) {
            fftw_wisdom = argv[++i];
        }
        else if (!strcmp(argv[i], "-log") && i + 1 < argc) {
            sep_path(argv[++i], paths[0], &log_lvl);
        }
        else if (!strcmp(argv[i], "-nmea") && i + 1 < argc) {
            sep_path(argv[++i], paths[1], tint + 1);
        }
        else if (!strcmp(argv[i], "-rtcm") && i + 1 < argc) {
            sep_path(argv[++i], paths[2], tint + 2);
        }
        else if (argv[i][0] == '-') {
            show_usage();
        }
        else {
            file = argv[i];
        }
    }
    sdr_func_init(fftw_wisdom);
    
    if (*paths[0]) {
        sdr_log_open(paths[0]);
        sdr_log_level((int)log_lvl);
    }
    if (dev_type == SDR_DEV_USB) {
        fmt = SDR_FMT_RAW8;
    }
    // new SDR receiver
    sdr_rcv_t *rcv = sdr_rcv_new(sigs, prns, fi, nch, fs, dop, fmt, IQ);
    
    if (dev_type == SDR_DEV_USB) {
        if (*conf_file) {
            (void)sdr_write_settings(conf_file, bus, port, 0);
            sdr_sleep_msec(100);
        }
        sdr_dev_t *dev = sdr_dev_open(bus, port);
        if (!dev) exit(-1);
        dp = (void *)dev;
    }
    else if (*file) {
        FILE *fp = fopen(file, "rb");
        if (!fp) {
            fprintf(stderr, "file open error: %s\n", file);
            exit(-1);
        }
        int ns = (fmt == SDR_FMT_RAW8 || IQ[0] == 1) ? 1 : 2;
        fseek(fp, (long)(toff * fs * ns), SEEK_SET);
        dp = (void *)fp;
    }
    else {
#ifdef WIN32 // set binary mode to stdin for Windows
        _setmode(_fileno(stdin), _O_BINARY);
#endif
        dp = (void *)stdin;
    }
    signal(SIGTERM, sig_func);
    signal(SIGINT, sig_func);
    
    uint32_t tt = sdr_get_tick();
    
    // start SDR receiver
    sdr_rcv_start(rcv, dev_type, dp, tint);
    
    while (!intr && rcv->state) { // wait for interrupt or file end
        sdr_sleep_msec(10);
    }
    // stop SDR receiver
    sdr_rcv_stop(rcv);
    
    // free SDR receiver
    sdr_rcv_free(rcv);
    
    if (tint[0] > 0.0) {
        printf("  TIME(s) = %.3f\n", (sdr_get_tick() - tt) * 1e-3);
    }
    sdr_log_close();
    
    if (dev_type == SDR_DEV_USB) {
        sdr_dev_close((sdr_dev_t *)dp);
    }
    else if (*file) {
        fclose((FILE *)dp);
    }
    return 0;
}
